/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as TokensAddressRouteImport } from './routes/tokens.$address'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiXCallbackRouteImport } from './routes/api/x/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensAddressRoute = TokensAddressRouteImport.update({
  id: '/tokens/$address',
  path: '/tokens/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXCallbackRoute = ApiXCallbackRouteImport.update({
  id: '/api/x/callback',
  path: '/api/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pulse': typeof PulseRoute
  '/studio': typeof StudioRoute
  '/tokens': typeof TokensRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/research': typeof ResearchRoute
  '/create': typeof CreateRoute
  '/analyze': typeof AnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pulse': typeof PulseRoute
  '/studio': typeof StudioRoute
  '/tokens': typeof TokensRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/research': typeof ResearchRoute
  '/create': typeof CreateRoute
  '/analyze': typeof AnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pulse': typeof PulseRoute
  '/studio': typeof StudioRoute
  '/tokens': typeof TokensRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/research': typeof ResearchRoute
  '/create': typeof CreateRoute
  '/analyze': typeof AnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/pulse'
    | '/studio'
    | '/tokens'
    | '/tokens/$address'
    | '/research'
    | '/create'
    | '/analyze'
    | '/api/auth/$'
    | '/api/x/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/pulse'
    | '/studio'
    | '/tokens'
    | '/tokens/$address'
    | '/research'
    | '/create'
    | '/analyze'
    | '/api/auth/$'
    | '/api/x/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboard'
    | '/pulse'
    | '/studio'
    | '/tokens'
    | '/tokens/$address'
    | '/research'
    | '/create'
    | '/analyze'
    | '/api/auth/$'
    | '/api/x/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  PulseRoute: typeof PulseRoute
  StudioRoute: typeof StudioRoute
  TokensRoute: typeof TokensRoute
  TokensAddressRoute: typeof TokensAddressRoute
  ResearchRoute: typeof ResearchRoute
  CreateRoute: typeof CreateRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiXCallbackRoute: typeof ApiXCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$address': {
      id: '/tokens/$address'
      path: '/tokens/$address'
      fullPath: '/tokens/$address'
      preLoaderRoute: typeof TokensAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/callback': {
      id: '/api/x/callback'
      path: '/api/x/callback'
      fullPath: '/api/x/callback'
      preLoaderRoute: typeof ApiXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  PulseRoute: PulseRoute,
  StudioRoute: StudioRoute,
  TokensRoute: TokensRoute,
  TokensAddressRoute: TokensAddressRoute,
  ResearchRoute: ResearchRoute,
  CreateRoute: CreateRoute,
  AnalyzeRoute: AnalyzeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiXCallbackRoute: ApiXCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
